api:
  host: 0.0.0.0
  port: 5000
  debug: false
  workers: 4

model:
  name: t5-base
  max_length: 150
  min_length: 40
  cache_dir: ./models/cache

database:
  url: sqlite:///financial_summaries.db

logging:
  level: INFO
  file: logs/financial_summarizer.log
  max_size: 10485760  # 10MB
  backup_count: 5

sec_edgar:
  user_agent: "Financial Summarizer App yourname@example.com"
  max_retries: 3
  timeout: 30
  backoff_factor: 2

environments:
  development:
    api:
      debug: true
      workers: 1
    logging:
      level: DEBUG
  
  production:
    api:
      debug: false
    logging:
      level: INFO 